name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main  # on default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Checkout gh-pages branch to get doc_templates
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Copy doc_templates to workspace
      run: |
        cp -r gh-pages/doc_templates ./

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install setuptools and wheel
      run: |
        pip install setuptools wheel

    - name: Install project dependencies
      run: |
        pip install -e .[accelerators]

    - name: Install pdoc3
      run: |
        pip install pdoc3

    - name: Generate documentation with MathJax support
      run: |
          pdoc --html --template-dir doc_templates . --output-dir temp_docs --config latex_math_renderer="'mathjax'"

    - name: Prepare docs directory for gh-pages
      run: |
        mkdir -p docs/docs
        cp -r temp_docs/hw2d* docs/docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./docs
        publish_branch: gh-pages 
        keep_files: true
